//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanPaymentCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanPaymentCalculator.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downpayment must be less then Amount.
        /// </summary>
        internal static string DownpaymentLessAmount {
            get {
                return ResourceManager.GetString("DownpaymentLessAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &quot;E&quot; for exit..
        /// </summary>
        internal static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Amount.
        /// </summary>
        internal static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DownPayment.
        /// </summary>
        internal static string InvalidDownPayment {
            get {
                return ResourceManager.GetString("InvalidDownPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidInterest.
        /// </summary>
        internal static string InvalidInterest {
            get {
                return ResourceManager.GetString("InvalidInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidTerm.
        /// </summary>
        internal static string InvalidTerm {
            get {
                return ResourceManager.GetString("InvalidTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be positive.
        /// </summary>
        internal static string MustBepositive {
            get {
                return ResourceManager.GetString("MustBepositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be greater than zero or positive.
        /// </summary>
        internal static string MustBepositiveOrGreaterZero {
            get {
                return ResourceManager.GetString("MustBepositiveOrGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a valid integer numerical value.
        /// </summary>
        internal static string NotValidInteger {
            get {
                return ResourceManager.GetString("NotValidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be less than 100.
        /// </summary>
        internal static string PersentLess {
            get {
                return ResourceManager.GetString("PersentLess", resourceCulture);
            }
        }
    }
}
